aws:
  bucket_name: "customer-sales-data-project"
  region: "us-east-1"

s3_directories:
  s3_customer_datamart_directory: "customer_data_mart"
  s3_sales_team_datamart_directory: "sales_data_mart"
  s3_source_directory: "sales_data/"
  s3_error_directory: "sales_data_error/"
  s3_processed_directory: "sales_data_processed/"
  s3_sales_team_data_mart_partitioned_directory: "sales_data_mart_partitioned"
  s3_bad_records_directory: "bad_records/"
  s3_invalid_records_directory: "invalid_records/"

database:
  name: "database_name"
  host: "host.docker.internal"
  port: "3306"
  user: "root"
  password: "user_password"
  driver: "com.mysql.cj.jdbc.Driver"

tables:
  staging_table: "staging_table"

  dimension:
    customer_table: "customer"
    product_table: "product"
    sales_team_table: "sales_team"
    store_table: "store"

  datamart:
    customers_monthly_sales_table: "customers_monthly_sales"
    sales_person_incentive_table: "sales_person_monthly_incentive"

mandatory_columns:
  - "customer_id"
  - "store_id"
  - "product_id"
  - "sales_person_id"
  - "sales_date"
  - "price"
  - "quantity"
  - "total_cost"
